{
 "title": "DataCore Swarm Listing Cache Service v8.3",
 "description": "Official dashboard for Swarm Listing Cache Service role in Swarm Gateway 8.3.0",
 "tags": [ "public" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(caringo_gateway_role{role=\"lcs\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gateway resources usage ",
   "type": "table",
   "description": "- *Load* - CPU capasity used (load average for last 1 minute divided by CPU cores count)\n- *CPU* - CPU usage\n- *Memory* - memory usage\n- *Filesystem* - filesystem usage\n- *Disk read* - maximum among all disks read rate\n- *Dist write* - maximum among all disks write rate\n- *Net recv* - maximum among all NIC's receive rate\n- *Net trans* - maximum among all NIC's transmit rate\n- *Net sock* - used network sockets \n- *TCP estab* - TCP established connections\n- *TCP tw* - TCP sockets in TIME-WAIT status",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"gateway-nodeexporter\"}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"gateway-nodeexporter\",mode=\"idle\"}[$__rate_interval])) by (instance)) * 100"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"gateway-nodeexporter\"} / (node_memory_MemTotal_bytes{job=~\"gateway-nodeexporter\"}))) * 100"
    },
    {
     "expr": "max((1 - (node_filesystem_free_bytes{job=~\"gateway-nodeexporter\"} / node_filesystem_size_bytes{job=~\"gateway-nodeexporter\"})) * 100) by (instance)"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"gateway-nodeexporter\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"gateway-nodeexporter\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"gateway-nodeexporter\"} - 0"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"gateway-nodeexporter\"} - 0"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"gateway-nodeexporter\"}[$__rate_interval])*8) by (instance)"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"gateway-nodeexporter\"}[$__rate_interval])*8) by (instance)"
    },
    {
     "expr": "avg(node_load1{job=~\"gateway-nodeexporter\"} * 100) by (instance) / count (node_cpu_seconds_total{job=~\"gateway-nodeexporter\", mode=\"system\"}) by (instance)"
    },
    {
     "expr": "node_sockstat_sockets_used{job=~\"gateway-nodeexporter\"}"
    },
    {
     "expr": "node_uname_info{job=~\"gateway-nodeexporter\"}",
     "legendFormat": "{{instance}}"
    },
    { "expr": "caringo_gateway_role", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Listing Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(caringo_gateway_elasticsearch_listing_succeeded_sum{instance=~\"$node\"}[5m]) / ( irate(caringo_gateway_elasticsearch_listing_succeeded_count{instance=~\"$node\"}[5m]) +1 )",
     "legendFormat": "{{query}}-OK-{{continuation}}"
    },
    {
     "expr": "irate(caringo_gateway_elasticsearch_listing_failed_sum{instance=~\"$node\"}[5m]) / irate(caringo_gateway_elasticsearch_listing_failed_count{instance=~\"$node\"}[5m])",
     "legendFormat": "{{query}}-FAIL-{{continuation}}"
    }
   ]
  },
  {
   "title": "Buckets Cached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "caringo_listingcache_buckets_cached",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backend Hit Ratio ( Cache Miss )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "caringo_listingcache_backend_query_count{method=\"list\",instance=~\"$node\"}  / caringo_listingcache_request_count{method=\"list\",instance=~\"$node\"}",
     "legendFormat": "Hit Ratio"
    },
    {
     "expr": "rate(caringo_listingcache_backend_query_count{method=\"list\",instance=~\"$node\"}[1h]) / rate(caringo_listingcache_request_count{method=\"list\",instance=~\"$node\"}[1h])",
     "legendFormat": "Hit Ratio Rate(1h)"
    }
   ]
  },
  { "title": "Listing Cache Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Listing cache request stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_request_count{instance=~\"$node\"}[5m])",
     "legendFormat": "{{method}} {{mode}}"
    },
    {
     "expr": "delta(caringo_listingcache_request_errors_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{method}} {{mode}} errors"
    }
   ]
  },
  {
   "title": "Listing Request Latency (delta 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_request_sum{instance=~\"$node\"}[5m]) / ( delta(caringo_listingcache_request_count{instance=~\"$node\"}[5m]) or vector(1) )",
     "legendFormat": "{{method}}-{{mode}}"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[10m]))",
     "legendFormat": "system cpu"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[10m]))",
     "legendFormat": "user cpu"
    }
   ]
  },
  {
   "title": "Records queried by source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_listed_recs_total{instance=~\"$node\"}[5m])",
     "legendFormat": "served"
    },
    {
     "expr": "sum(delta(caringo_listingcache_cache_query_recs_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "queried from disk cache"
    },
    {
     "expr": "sum(delta(caringo_listingcache_backend_query_recs_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "queried from ES"
    }
   ]
  },
  {
   "title": "Number of listing requests served",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_request_count{instance=~\"$node\",method=\"list\"}[5m])",
     "legendFormat": "{{method}} {{mode}}"
    }
   ]
  },
  {
   "title": "Flush Stats",
   "type": "timeseries",
   "description": "Flushing in-memory records to disk cache",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_flushes_done_total{instance=~\"$node\"}[5m])",
     "legendFormat": "flushes done"
    },
    {
     "expr": "caringo_listingcache_flushes_pending{instance=~\"$node\"}",
     "legendFormat": "flushes pending"
    }
   ]
  },
  {
   "title": "Trim Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_trims_done_total{instance=~\"$node\"}[5m])",
     "legendFormat": "trims done"
    },
    {
     "expr": "caringo_listingcache_trims_pending{instance=~\"$node\"}",
     "legendFormat": "trims pending"
    }
   ]
  },
  {
   "title": "Number of records served",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_listed_recs_total{instance=~\"$node\"}[5m])",
     "legendFormat": "recs {{mode}}"
    }
   ]
  },
  {
   "title": "Number of queries per source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(caringo_listingcache_request_count{method=\"list\",instance=~\"$node\"}[5m]))",
     "legendFormat": "listings served"
    },
    {
     "expr": "sum(delta(caringo_listingcache_cache_query_count{instance=~\"$node\"}[5m]))",
     "legendFormat": "disk cache queries"
    },
    {
     "expr": "sum(delta(caringo_listingcache_backend_query_count{instance=~\"$node\"}[5m]))",
     "legendFormat": "ES queries"
    }
   ]
  },
  {
   "title": "Pull Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_folder_pulls_done_total{instance=~\"$node\"}[5m])",
     "legendFormat": "pulls done"
    },
    {
     "expr": "caringo_listingcache_folder_pulls_pending{instance=~\"$node\"}",
     "legendFormat": "pulls pending"
    }
   ]
  },
  {
   "title": "Folders  in mem cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "expr": "caringo_listingcache_mem_cached{instance=~\"$node\"}",
     "legendFormat": "folders cached"
    },
    {
     "expr": "delta(caringo_listingcache_mem_evicted_total{instance=~\"$node\"}[5m])",
     "legendFormat": "folders evicted"
    }
   ]
  },
  {
   "title": "Number of records queried from ES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_backend_query_recs_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{method}} {{mode}}"
    }
   ]
  },
  {
   "title": "Number of ES Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_backend_query_count{instance=~\"$node\"}[5m])",
     "legendFormat": "{{method}} {{mode}}"
    }
   ]
  },
  {
   "title": "Bytes in disk cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "caringo_listingcache_disk_cached_bytes{instance=~\"$node\"}",
     "legendFormat": "bytes cached"
    },
    {
     "expr": "caringo_listingcache_disk_evicted_bytes{instance=~\"$node\"}",
     "legendFormat": "bytes evicted"
    }
   ]
  },
  {
   "title": "Folders in disk cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "targets": [
    {
     "expr": "caringo_listingcache_disk_cached{instance=~\"$node\"}",
     "legendFormat": "folders cached"
    },
    {
     "expr": "delta(caringo_listingcache_disk_evicted{instance=~\"$node\"}[5m])",
     "legendFormat": "folders evicted"
    }
   ]
  },
  {
   "title": "Number of records queried from disk cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_cache_query_recs_total{instance=~\"$node\"}[5m])",
     "legendFormat": "recs {{method}} {{mode}}"
    }
   ]
  },
  {
   "title": "Number of disk cache queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(caringo_listingcache_cache_query_count{instance=~\"$node\"}[5m])",
     "legendFormat": "{{method}} {{mode}}"
    }
   ]
  },
  {
   "title": "DBHandle Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "caringo_listingcache_dbhandle_cached{instance=~\"$node\"}",
     "legendFormat": "dbhandles cached"
    },
    {
     "expr": "delta(caringo_listingcache_dbhandle_evicted_total{instance=~\"$node\"}[5m])\n",
     "legendFormat": "dbhandles evicted"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "caringo_listingcache_memory_used{instance=~\"$node\"}",
     "legendFormat": "mem in use"
    }
   ]
  }
 ]
}