{
 "title": "DataCore Swarm Health Processor v2.1",
 "description": "internal dashboard for health processor on Swarm 17",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(caringo_swarm_health_cycle,instance)"
    }
   },
   { "name": "max", "query": "500" },
   {
    "name": "drive",
    "query": {
     "query": "label_values(caringo_swarm_volume_stats_defrag_last_run_time_sec,volume_dev)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global HP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global  HP Exam Speed (streams / hr )",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(caringo_swarm_health_examined[1h]) * 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trapped Space (delta) Per Instance (1h sample)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(delta(caringo_swarm_volume_trapped{volume_dev=~\"$drive\"}[1h])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Trapped Space (delta)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "delta(caringo_swarm_volume_trapped{instance=~\"$instance\",volume_dev=~\"$drive\"}[1h])",
     "legendFormat": "{{volume_dev}}-trapped"
    }
   ]
  },
  {
   "title": "TRAPPED",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(caringo_swarm_volume_trapped) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(caringo_swarm_volume_trapped) ",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Global  HP Defrag Speed (streams / hr )",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(delta(caringo_swarm_volume_stats_defrag_ongoing_streams_processed{volume_dev=~\"$drive\"}[60m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FREE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(caringo_swarm_volume_free) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(caringo_swarm_volume_free) ",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "CPU Stats for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Overall CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[10m]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[10m]),1)) )),1)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[10m]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  {
   "title": "CPU load over time（%）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[30m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[30m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[30m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[30m])",
     "legendFormat": "{{device}}_I/O%"
    }
   ]
  },
  { "title": "Node HP Stats for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "HP Cycle",
   "type": "stat",
   "description": "Current HP cycle",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_health_cycle{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Examined",
   "type": "stat",
   "description": "Total amount of streams examined so far.",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_health_examined{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relocated On disk",
   "type": "stat",
   "description": "streams relocated locally on disk",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_health_relocated{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "defrag relocated (streams/hr)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(caringo_swarm_volume_stats_defrag_ongoing_streams_relocated_on_disk{instance=~\"$instance\",volume_dev=~\"$drive\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "stat",
   "description": "Total streams on this chassis.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(caringo_swarm_volume_streams{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exam Speed ( streams/hr )",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(caringo_swarm_health_examined{instance=~\"$instance\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "defrag processed (streams/hr)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(caringo_swarm_volume_stats_defrag_ongoing_streams_processed{instance=~\"$instance\",volume_dev=~\"$drive\"}[60m])) >0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offloaded to the Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_health_offloaded{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exam Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "caringo_swarm_node_examq{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Integrity Verified (streams/hr)",
   "type": "timeseries",
   "description": "Total streams verified for integrity by HP so far.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(caringo_swarm_health_verified{instance=~\"$instance\"}[1h])",
     "legendFormat": "{{instance}} verified"
    }
   ]
  },
  {
   "title": "Streams examined/relocated (streams/hr)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(rate(caringo_swarm_health_relocated{instance=~\"$instance\"}[1h]) < $max ) * 3600",
     "legendFormat": "{{instance}} "
    },
    {
     "expr": "(rate(caringo_swarm_health_offloaded{instance=~\"$instance\"}[1h]) < $max ) * 3600",
     "legendFormat": "{{instance}} -offloaded"
    },
    {
     "expr": "(rate(caringo_swarm_health_examined{instance=~\"$instance\"}[1h]) < $max ) *3600",
     "legendFormat": "{{instance}} -examined"
    }
   ]
  },
  {
   "title": "Drive Statistics for $instance / $drive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "State: $drive",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_state{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free MB ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_free{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last HP Cycle exit code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_stats_defrag_last_termination_state{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_streams{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ECRS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_ecrs{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_errors{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HP Active Defrag State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 2, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_stats_defrag_ongoing_state{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trapped MB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_trapped{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity MB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_capacity{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FVRS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_fvrs{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "w_await (ms)",
   "type": "timeseries",
   "description": "Average time needed to service a write I/O request by the drive",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$instance\",device=~\"$drive\"}[1h]) / rate(node_disk_writes_completed_total{instance=~\"$instance\",device=~\"$drive\"}[1h])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "r_await (ms)",
   "type": "timeseries",
   "description": "average time needed to service an I/O read request by the drive",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$instance\",device=~\"$drive\"}[1h]) / rate(node_disk_reads_completed_total{instance=~\"$instance\",device=~\"$drive\"}[1h])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Free vs Trapped Space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "caringo_swarm_volume_free{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "{{volume_dev}}-free"
    },
    {
     "expr": "caringo_swarm_volume_trapped{instance=~\"$instance\",volume_dev=~\"$drive\"}",
     "legendFormat": "{{volume_dev}}-trapped"
    }
   ]
  },
  {
   "title": "Defrag active Streams processed ($drive) streams/hr",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(caringo_swarm_volume_stats_defrag_ongoing_streams_processed{instance=~\"$instance\",volume_dev=~\"$drive\"}[60m]) * 3600",
     "legendFormat": "{{volume_dev}}-rate"
    }
   ]
  }
 ]
}