{
 "title": "DataCore Swarm Gateway v8.3",
 "description": "official dashboard for Swarm gateway v8.3 and above",
 "tags": [ "public" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gateway",
    "query": {
     "query": "label_values(caringo_gateway_role{role=\"s3\"},instance)"
    }
   },
   {
    "name": "interval",
    "query": "2m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "ds_prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Load 5mins",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=~\"$gateway\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(process_open_fds{instance=~\"$gateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(caringo_gateway_connection_leased_gauge{backend=\"swarm\",instance=~\"$gateway\"})",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "Operations (5m)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(caringo_gateway_request_count{instance=~\"$gateway\"}[5m]))",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "Operations (24h)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(caringo_gateway_request_count{instance=~\"$gateway\"}[24h]))",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "Gateway Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(topk(1,caringo_gateway_info{instance=~\"$gateway\"}), \"version\", \"$1\", \"version\", \"^([0-9].[0-9].[0-9]).*\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backends",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(caringo_gateway_live_backendnode_count{instance=~\"$gateway\",backend=\"swarm\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elasticsearch (min)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(caringo_gateway_live_backendnode_count{backend=\"es\",job=~\"$gateway\"})"
    }
   ]
  },
  {
   "title": "Gateway Roles",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "caringo_gateway_role{instance=~\"$gateway\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Network IO {needs node_exporter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$gateway',device!~'tap.*',device!~'lo.*'}[$interval])",
     "legendFormat": "{{instance}}/{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$gateway',device!~'tap.*',device!~'lo.*'}[$interval])",
     "legendFormat": "{{instance}}/{{device}}_out"
    }
   ]
  },
  {
   "title": "backend connections (swarm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "caringo_gateway_connection_available_gauge{instance=~\"$gateway\",backend=\"swarm\"}",
     "legendFormat": "avail[{{instance}}]"
    },
    {
     "expr": "caringo_gateway_connection_leased_gauge{instance=~\"$gateway\",backend=\"swarm\"}",
     "legendFormat": "leased[{{instance}}]"
    },
    {
     "expr": "caringo_gateway_connection_pending_gauge{instance=~\"$gateway\",backend=\"swarm\"}",
     "legendFormat": "pending[{{instance}}]"
    }
   ]
  },
  {
   "title": "Operations per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(caringo_gateway_request_count{instance=~\"$gateway\"}[1h])) by (method)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$gateway\",area=\"heap\"}",
     "legendFormat": "JVM Heap Used[{{instance}}]"
    }
   ]
  },
  {
   "title": "JVM CPU Load 5mins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=~\"$gateway\"}[5m]))",
     "legendFormat": "CPU load"
    }
   ]
  },
  { "title": "Operations Overview (Hourly)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Operations per protocol (ops/h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(caringo_gateway_request_latency_count{instance=~\"$gateway\"}[1h])) by (protocol) >0",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "S3 Status Code (ops/h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(caringo_gateway_status_code_count{instance=~\"$gateway\",protocol=\"s3\"}[1h])) by (method,status)\n",
     "legendFormat": "{{method}}_{{status}}"
    }
   ]
  },
  {
   "title": "Http Status Codes  (all protocols ops/h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(caringo_gateway_status_code_count{instance=~\"$gateway\"}[1h])) by (status)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "SCSP Status Code  (ops/h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(caringo_gateway_status_code_count{instance=~\"$gateway\",protocol=\"scsp\"}[1h])) by (method,status)\n",
     "legendFormat": "{{method}}_{{status}}"
    }
   ]
  },
  {
   "title": "S3 Status Code by Operation Type (ops/h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(caringo_gateway_status_code_count{instance=~\"$gateway\",protocol=\"s3\"}[1h])) by (scope)\n",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Requests by method delta stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(caringo_gateway_request_count{instance=~\"$gateway\"}[1h])) by (method)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Operations Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Operations per protocol (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(caringo_gateway_request_latency_count{instance=~\"$gateway\"}[5m])) by (protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "S3 Status Code (5min) (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(caringo_gateway_status_code_count{instance=~\"$gateway\",protocol=\"s3\"}[5m])) by (method,status)\n",
     "legendFormat": "{{method}}_{{status}}"
    }
   ]
  },
  {
   "title": "Http Status Codes (5min)  (all protocols ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(caringo_gateway_status_code_count{instance=~\"$gateway\"}[5m])) by (status)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "SCSP Status Code (5min) (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(caringo_gateway_status_code_count{instance=~\"$gateway\",protocol=\"scsp\"}[5m])) by (method,status)\n",
     "legendFormat": "{{method}}_{{status}}"
    }
   ]
  },
  {
   "title": "S3 Status Code (5min) (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(caringo_gateway_status_code_count{instance=~\"$gateway\",protocol=\"s3\"}[5m])) by (scope)\n",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Requests by method delta stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(caringo_gateway_request_count{instance=~\"$gateway\"}[5m])) by (method)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Listing Refresh Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(caringo_gateway_elasticsearch_refresh_success_sum{instance=~\"$gateway\"}[5m]) /( irate(caringo_gateway_elasticsearch_refresh_success_count{instance=~\"$gateway\"}[5m]) + 1)",
     "legendFormat": "success"
    },
    {
     "expr": "irate(caringo_gateway_elasticsearch_refresh_failure_sum{instance=~\"$gateway\"}[5m]) / irate(caringo_gateway_elasticsearch_refresh_failure_count{instance=~\"$gateway\"}[5m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Dead backends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "caringo_gateway_dead_backendnode_count{instance=~\"$gateway\",backend=\"swarm\"}",
     "legendFormat": "dead[{{instance}}]"
    },
    {
     "expr": "caringo_gateway_live_backendnode_count{instance=~\"$gateway\",backend=\"swarm\"}",
     "legendFormat": "live[{{instance}}]"
    }
   ]
  },
  { "title": "LC/XMD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "LCS Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(caringo_listingcacheclient_request_count{instance=~\"$gateway\"}[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Extrinsic Metadata Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(caringo_extrinsic_request_count{instance=~\"$gateway\"}[5m])",
     "legendFormat": "{{kind}} count"
    },
    {
     "expr": "delta(caringo_extrinsic_request_errors{instance=~\"$gateway\"}[5m])",
     "legendFormat": "{{kind}} errors"
    }
   ]
  },
  {
   "title": "LCS Request Errors/Timeouts/Redirects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "delta(caringo_listingcacheclient_request_errors_total{instance=~\"$gateway\"}[5m])",
     "legendFormat": "{{method}} errors"
    },
    {
     "expr": "delta(caringo_listingcacheclient_request_redirects_total{instance=~\"$gateway\"}[5m])",
     "legendFormat": "{{method}} redirects"
    },
    {
     "expr": "delta(caringo_listingcacheclient_request_timeouts_total{instance=~\"$gateway\"}[5m])",
     "legendFormat": "{{method}} timeouts"
    }
   ]
  },
  {
   "title": "Extrinsic Metadata Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "caringo_extrinsic_request_sum{instance=~\"$gateway\"} / caringo_extrinsic_request_count{instance=~\"$gateway\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}