{
 "title": "Cluster Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "noderole",
    "label": "Node Role",
    "query": {
     "query": "label_values(kube_node_role,role)"
    }
   },
   { "name": "sparenodesfactor", "label": "Spare Nodes", "query": "0,1,1.5,2" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\", status!=\"false\"})\n+\nsum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\", status!=\"false\"}) by (condition)",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "Unschedulable"
    }
   ]
  },
  {
   "title": "Workload",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "total" },
    { "expr": "sum(kube_node_role) by (role)", "legendFormat": "{{role}}" }
   ]
  },
  {
   "title": "Cores Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\n(\nsum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"worker\"})\n-\navg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"worker\"}) * $sparenodesfactor\n)\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"worker\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cores Used Top Node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,\n  100\n  /\n  sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) by (node)\n  *\n  sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)\n)"
    }
   ]
  },
  {
   "title": "CPU Cores Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\n(\n  sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"})\n  -\n  avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() kube_node_role{role=\"$noderole\"})\n  * $sparenodesfactor\n)\n*\n(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory  Used Top Node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,\n  100\n  /\n  sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) by (node)\n  *\n  (\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)\n  )\n)"
    }
   ]
  },
  {
   "title": "Memory usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)\n-\nsum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))"
    }
   ]
  },
  {
   "title": "Disk Read & Write by Node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
     "legendFormat": "{{node}} (read)"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node) * -1",
     "legendFormat": "{{node}} (write)"
    }
   ]
  },
  {
   "title": "Network Reveive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))"
    }
   ]
  },
  {
   "title": "Network Bandwith (receive & transmit) by Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
     "legendFormat": "{{node}} (receive)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node) * -1",
     "legendFormat": "{{node}} (transmit)"
    }
   ]
  },
  { "title": "Capacity Management - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Comments",
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 28 },
   "options": {
    "content": "- CPU / Memory allocatable (brutto) = Total allocatable  \n- CPU / Memory allocatable (netto) = Total allocatable - spare nodes ---> All requested, used and limits values are calculated with the allocatable (netto) values"
   }
  },
  {
   "title": "Nodes ($noderole)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores (brutto)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores (netto)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"})\n-\navg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() kube_node_role{role=\"$noderole\"}) * $sparenodesfactor"
    }
   ]
  },
  {
   "title": "Memory (brutto)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory (netto)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"})\n-\navg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() kube_node_role{role=\"$noderole\"}) * $sparenodesfactor)"
    }
   ]
  },
  {
   "title": "Cores Requested (from netto)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() kube_node_role{role=\"$noderole\"}) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores Used (from netto)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\n(\nsum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"worker\"})\n-\navg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"worker\"}) * $sparenodesfactor\n)\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"worker\"}))"
    }
   ]
  },
  {
   "title": "Cores Used (from requested)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))"
    }
   ]
  },
  {
   "title": "Cores Limits (from netto)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() kube_node_role{role=\"$noderole\"}) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) - avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() kube_node_role{role=\"$noderole\"}) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory Used (from netto)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\n(\n  sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"})\n  -\n  avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() kube_node_role{role=\"$noderole\"})\n  * $sparenodesfactor\n)\n*\n(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n)"
    }
   ]
  },
  {
   "title": "Memory Used (from requested)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n*\n(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n)"
    }
   ]
  },
  {
   "title": "Memory Limits (from netto)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) - avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() kube_node_role{role=\"$noderole\"}) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_limits{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores Requested (apps)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores Used (apps)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores Wasted (apps)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n-\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*|openshift-.*\"}[5m]) * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) > 0"
    }
   ]
  },
  {
   "title": "Cores Limits (apps)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory Requested (apps)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace!~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory Used (apps)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left(role) kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory Wasted (apps)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace!~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n-\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) > 0"
    }
   ]
  },
  {
   "title": "Memory Limits (apps)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace!~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores Requested (k8s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores Used (k8s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*|openshift-.*\"}[5m]) * on(node) group_left(role) kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores Wasted (k8s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n-\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*|openshift-.*\"}[5m]) * on(node) group_left(role) kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores Limits (k8s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory Requested (k8s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory Used (k8s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left(role) kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory Wasted (k8s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"kube-.*|cattle-.*|openshift-.*\"} \n  * on(pod, namespace) group_left() \n  (kube_pod_status_phase{phase=\"Running\"}==1) \n  * on(node) group_left() \n  kube_node_role{role=\"$noderole\"}\n)\n-\nsum(\n  container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*|openshift-.*\"} \n  * on(pod, namespace) group_left() \n  (kube_pod_status_phase{phase=\"Running\"}==1) \n  * on(node) group_left() \n  kube_node_role{role=\"$noderole\"}\n)\n"
    }
   ]
  },
  {
   "title": "Memory Limits (k8s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"kube-.*|cattle-.*|openshift-.*\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Cores Requested",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\"} \n  * on(pod, namespace) group_left(node) \n    (kube_pod_info * on(node) group_left(role) kube_node_role{role=\"$noderole\"})\n  * on(pod, namespace) group_left() \n    (kube_pod_status_phase{phase=\"Running\"}==1)\n)\n"
    }
   ]
  },
  {
   "title": "Cores Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))"
    }
   ]
  },
  {
   "title": "Cores Wasted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\"} \n  * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) \n  * on(node) group_left() kube_node_role{role=\"$noderole\"}\n)\n-\nsum(\n  rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\"}[5m]) \n  * on(node) group_left(role) kube_node_role{role=\"$noderole\"}\n) > 0\n"
    }
   ]
  },
  {
   "title": "Cores Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n-\nsum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))"
    }
   ]
  },
  {
   "title": "Memory Wasted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"memory\"} \n  * on(pod, namespace) group_left() \n  (kube_pod_status_phase{phase=\"Running\"}==1) \n  * on(node) group_left() \n  kube_node_role{role=\"$noderole\"}\n)\n-\nsum(\n  container_memory_working_set_bytes{container=\"\", pod!=\"\"} \n  * on(pod, namespace) group_left() \n  (kube_pod_status_phase{phase=\"Running\"}==1) \n  * on(node) group_left() \n  kube_node_role{role=\"$noderole\"}\n)\n"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
    }
   ]
  },
  {
   "title": "CPU Cores by Node",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (node)"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
    },
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (node)\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
    },
    {
     "expr": "100\n/\nsum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) by (node)\n*\navg(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (node)"
    },
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (node)\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
    }
   ]
  },
  {
   "title": "Memory by Node",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (node)"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)\n-\nsum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
    },
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (node)\n*\n(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)\n)"
    },
    {
     "expr": "avg(sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))) by (node)\n-\navg(sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))) by (node)"
    },
    {
     "expr": "100\n/\nsum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) by (node)\n*\navg(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"worker\"})) by (node)\n-\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"worker\"})) by (node)\n) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (node)"
    },
    {
     "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (node)\n*\n(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)\n)"
    }
   ]
  },
  {
   "title": "Namespaces Wasting CPU Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (namespace)\n-\nsum(rate(container_cpu_usage_seconds_total{container=\"\",pod!=\"\"}[5m]) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (namespace) > 0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespaces Wasting Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"}) by (namespace)\n-\nsum(container_memory_working_set_bytes{container=\"\",pod!=\"\"}* on(node) group_left() kube_node_role{role=\"$noderole\"}) by (namespace) > 0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Capacity Management - Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cores Requested (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() kube_node_role{role=\"$noderole\"}) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Requested (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total"
      },
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s"
      },
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps"
      }
     ]
    },
    {
     "title": "Cores Allocatable & Requested",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)",
       "legendFormat": "allocatable (netto)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (requested)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (requested)"
      }
     ]
    },
    {
     "title": "Memory Requested (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) - avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() kube_node_role{role=\"$noderole\"}) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Requested (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total"
      },
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s"
      },
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps"
      }
     ]
    },
    {
     "title": "Memory Allocatable & Requested",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)",
       "legendFormat": "allocatable (netto)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (requested)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (requested)"
      }
     ]
    },
    {
     "title": "Cores Used (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\nsum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"worker\"})\n-\navg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"worker\"}) * $sparenodesfactor\n)\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"worker\"}))"
      }
     ]
    },
    {
     "title": "Cores Used (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\n(\nsum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n-\navg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor\n)\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))",
       "legendFormat": "total"
      },
      {
       "expr": "100\n/\n(\nsum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n-\navg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor\n)\n*\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s"
      },
      {
       "expr": "100\n/\n(\nsum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n-\navg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor\n)\n*\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps"
      }
     ]
    },
    {
     "title": "Cores Allocatable & Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)",
       "legendFormat": "allocatable (netto)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))",
       "legendFormat": "total (used)"
      }
     ]
    },
    {
     "title": "Memory Used (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"})\n  -\n  avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() kube_node_role{role=\"$noderole\"})\n  * $sparenodesfactor\n)\n*\n(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n)"
      }
     ]
    },
    {
     "title": "Memory Used (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n  -\n  avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n  * $sparenodesfactor\n)\n*\n(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))\n)",
       "legendFormat": "total"
      },
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n  -\n  avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n  * $sparenodesfactor\n)\n*\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s"
      },
      {
       "expr": "100\n/\n(\n  sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n  -\n  avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n  * $sparenodesfactor\n)\n*\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps"
      }
     ]
    },
    {
     "title": "Memory Allocatable & Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)",
       "legendFormat": "allocatable (netto)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (node)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))\n-\nsum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))",
       "legendFormat": "total (used)"
      }
     ]
    },
    {
     "title": "Cores Used (from requested)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))"
      }
     ]
    },
    {
     "title": "Cores Used (from requested)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))",
       "legendFormat": "total"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps"
      }
     ]
    },
    {
     "title": "Cores Requested & Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "requested"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))",
       "legendFormat": "total (used)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (used)"
      }
     ]
    },
    {
     "title": "Memory Used (from requested)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n*\n(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))\n)"
      }
     ]
    },
    {
     "title": "Memory Used (from requested)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\n(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))\n  -\n  sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))\n)",
       "legendFormat": "total"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps"
      }
     ]
    },
    {
     "title": "Memory Requested & Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "requested"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))\n-\nsum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))",
       "legendFormat": "total (used)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (used)"
      }
     ]
    },
    {
     "title": "Cores Wasted (from requested)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n*\n(sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n-\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\"}[5m]) * on(node) group_left(role) kube_node_role{role=\"$noderole\"}))"
      }
     ]
    },
    {
     "title": "Cores Wasted (from requested)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\n(sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n-\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))",
       "legendFormat": " apps (wasted)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\n(sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n-\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)))",
       "legendFormat": "k8s (wasted)"
      }
     ]
    },
    {
     "title": "Cores Requested, Used & Wasted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n-\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (wasted)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n-\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (wasted)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (requested)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (requested)"
      }
     ]
    },
    {
     "title": "Memory Wasted (from requested)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n*\n(\n  sum(kube_pod_container_resource_requests{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n  -\n  sum(container_memory_working_set_bytes{container=\"\", pod!=\"\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left(role) kube_node_role{role=\"$noderole\"})\n)"
      }
     ]
    },
    {
     "title": "Memory Wasted (from requested)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\n(\n  sum(kube_pod_container_resource_requests{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n  -\n  sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n)",
       "legendFormat": " apps (wasted)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\n(\n  sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n  -\n  sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n)",
       "legendFormat": "k8s (wasted)"
      }
     ]
    },
    {
     "title": "Memory Requested, Used & Wasted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n-\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (wasted)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n-\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (wasted)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (requested)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (requested)"
      }
     ]
    },
    {
     "title": "Cores Limits (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() kube_node_role{role=\"$noderole\"}) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Limits (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total"
      },
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s"
      },
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps"
      }
     ]
    },
    {
     "title": "Cores Limits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps"
      }
     ]
    },
    {
     "title": "Memory Limits (from netto)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) kube_node_role{role=\"$noderole\"}) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() kube_node_role{role=\"$noderole\"}) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_limits{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Limits (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_limits{resource=\"memory\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total"
      },
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s"
      },
      {
       "expr": "100\n/\n(sum(kube_node_status_allocatable{resource=\"memory\"} * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node)) - avg(kube_node_status_allocatable{resource=\"cpu\"} * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node)) * $sparenodesfactor)\n*\nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps"
      }
     ]
    },
    {
     "title": "Memory Limits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Cores Used (from Limits)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n*\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\"}[5m]) * on(node) group_left(role) kube_node_role{role=\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Cores Limits (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(rate(container_cpu_usage_seconds_total{container=\"\",}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total (used)"
      }
     ]
    },
    {
     "title": "Cores Limits & Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (limits)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (limits)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"\", pod!=\"\"}[5m]) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total (limits)"
      }
     ]
    },
    {
     "title": "Memory Used (from Limits)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"memory\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left() kube_node_role{role=\"$noderole\"})\n*\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1) * on(node) group_left(role) kube_node_role{role=\"$noderole\"})"
      }
     ]
    },
    {
     "title": "Memory Limits (from netto)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "100\n/\nsum(kube_pod_container_resource_limits{resource=\"memory\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))\n*\nsum(container_memory_working_set_bytes{container=\"\", pod!=\"\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total (used)"
      }
     ]
    },
    {
     "title": "Memory Limits & Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace!~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "apps (limits)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"kube-.*|cattle-.*openshift-.*\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "k8s (limits)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container=\"\", pod!=\"\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total (used)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} * on(pod, namespace) group_left() (topk(1,kube_pod_status_phase{phase=\"Running\"}==1) by (pod)) * on(node) group_left() topk(1,kube_node_role{role=\"$noderole\"}) by (node))",
       "legendFormat": "total (limits)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores Usage by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Cores Usage by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\ncount((node_cpu_seconds_total{mode=\"idle\"}) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)\n*\nsum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)\n-\nsum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory Usage by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\nsum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node ))) by (node)\n*\n(\n sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node ))) by (node)\n -\n sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"} * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node ))) by (node)\n)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Storage Usage by Node",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      },
      {
       "expr": "sum(rate(node_disk_reads_completed_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      },
      {
       "expr": "sum(rate(node_disk_writes_completed_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      },
      {
       "expr": "sum(rate(node_disk_read_time_seconds_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)\n/\nsum(rate(node_disk_reads_completed_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      },
      {
       "expr": "sum(rate(node_disk_write_time_seconds_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)\n/\nsum(rate(node_disk_writes_completed_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      }
     ]
    },
    {
     "title": "Filesystem Usage by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max((node_filesystem_size_bytes{mountpoint!~\"/run.*\"}) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (mountpoint,node)\n-\nmax((node_filesystem_avail_bytes{mountpoint!~\"/run.*\"}) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (mountpoint,node)",
       "legendFormat": "{{node}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem Usage by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\nmax((node_filesystem_size_bytes{mountpoint!~\"/run.*\"}) * on(instance,pod) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (mountpoint,node)\n*\n(\n  max((node_filesystem_size_bytes{mountpoint!~\"/run.*\"}) * on(instance,pod) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (mountpoint,node)\n  -\n  max((node_filesystem_avail_bytes{mountpoint!~\"/run.*\"}) * on(instance,pod) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (mountpoint,node)\n)",
       "legendFormat": "{{node}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "IOWait by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n/\ncount((node_cpu_seconds_total{mode=\"idle\"}) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)\n*\nsum(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read Storage Troughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read Storage IOPS by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_reads_completed_total[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read Wait by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_time_seconds_total[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)\n/\nsum(rate(node_disk_reads_completed_total[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Storage Troughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Storage IOPS by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_writes_completed_total[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Wait by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_write_time_seconds_total[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)\n/\nsum(rate(node_disk_writes_completed_total[5m]) * on(instance) group_left(node) (label_replace(topk(1,node_uname_info) by (instance), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Network Usage by Node",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      },
      {
       "expr": "sum(rate(node_network_receive_packets_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      },
      {
       "expr": "sum(rate(node_network_transmit_packets_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      },
      {
       "expr": "sum(rate(node_network_receive_drop_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      },
      {
       "expr": "sum(rate(node_network_transmit_drop_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) kube_node_role{role=\"$noderole\"})) by (node)"
      }
     ]
    },
    {
     "title": "Reveive Network Bandwith by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Reveive Network Packets by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_packets_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Transmit Network Bandwith by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Transmit Network Packets by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_packets_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Reveive Network Packets Dropped by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_drop_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Transmit Network Packets Dropped by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_drop_total[5m]) * on(instance) group_left(node) (label_replace((node_uname_info), \"node\", \"$1\", \"nodename\", \"(.*)\") * on(node) group_left(role) topk(1,kube_node_role{role=\"$noderole\"}) by (node))) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}