{
 "title": "Harbor 15792",
 "description": "修改自harbor官方仓库：https://github.com/goharbor/harbor/edit/master/contrib/grafana-dashborad/metrics-example.json",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(node_uname_info, hostname)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(harbor_system_info{}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "component up status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{instance=~\"172.16.31.2:9090\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Project repo total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_project_repo_total{instance=~\"$instance\", public=\"true\"}",
     "legendFormat": "Pub - {{project_name}}"
    },
    {
     "expr": "harbor_project_repo_total{instance=~\"$instance\", public=\"false\"}",
     "legendFormat": "Priv - {{project_name}} "
    }
   ]
  },
  {
   "title": "Quota Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "harbor_project_quota_usage_byte{instance=~\"$instance\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "artifact pulled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_artifact_pulled{instance=~\"$instance\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Project total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_project_total{instance=~\"$instance\", public=\"true\"}",
     "legendFormat": "Public"
    },
    {
     "expr": "harbor_project_total{instance=~\"$instance\", public=\"false\"}",
     "legendFormat": "Private"
    }
   ]
  },
  { "title": "Genertal metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Filesystem Inodes Used",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - ( node_filesystem_files_free{instance=~\"172.16.31.2:9100\"} / node_filesystem_files{instance=~\"172.16.31.2:9100\"} * 100 )",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{hostname=\"$hostname\", device=\"eth0\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{hostname=\"$hostname\", device=\"eth0\"}[1m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "系统平均负载5m&15m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_load5/ count(node_cpu_seconds_total{mode=\"idle\", hostname=~\"$hostname\"}) without (cpu,mode))*100",
     "legendFormat": "5min"
    },
    {
     "expr": "(node_load15/ count(node_cpu_seconds_total{mode=\"idle\", hostname=~\"$hostname\"}) without (cpu,mode))*100",
     "legendFormat": "15min"
    }
   ]
  },
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "API request time 0.5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "API request time 0.9",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "request time 0.99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "harbor core request total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(harbor_core_http_request_total[5m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "harbor core inflight request",
   "type": "timeseries",
   "description": "“飞行中的请求”，请求发出但还没有收到响应的数量。",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_core_http_inflight_requests"
    }
   ]
  },
  { "title": "JobService Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "task latency（任务延迟）",
   "type": "timeseries",
   "description": "time period from last process of task queue",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_task_queue_latency{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "task concurrency（任务并发）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_task_concurrency{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "task queue pending size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_task_queue_size{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "number of running scheduled job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "harbor_task_scheduled_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "tasks per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "rate(harbor_jobservice_task_total{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "task process time 0.5",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "harbor_jobservice_task_process_time_seconds{instance=~\"$instance\", quantile=\"0.5\"}"
    }
   ]
  },
  {
   "title": "task process time 0.9",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "harbor_jobservice_task_process_time_seconds{instance=~\"$instance\",quantile=\"0.9\"}"
    }
   ]
  },
  {
   "title": "task process time 0.99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "harbor_jobservice_task_process_time_seconds{instance=~\"$instance\",quantile=\"0.99\"}"
    }
   ]
  },
  { "title": "Registry Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Registry request inflight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "registry_http_in_flight_requests{instance=~\"$instance\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Registry request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "rate(registry_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{code}} - {{handler}}"
    }
   ]
  },
  {
   "title": "registry storage cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "rate(registry_storage_cache_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "registry request time 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(registry_http_request_duration_seconds_bucket{instance=~\"$instance\"}[10m]))",
     "legendFormat": "{{method}} - {{handler}}"
    }
   ]
  },
  {
   "title": "registry request time 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(registry_http_request_duration_seconds_bucket{instance=~\"$instance\"}[10m]))",
     "legendFormat": "{{method}} - {{handler}}"
    }
   ]
  },
  {
   "title": "registry request time 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(registry_http_request_duration_seconds_bucket{instance=~\"$instance\"}[10m]))",
     "legendFormat": "{{method}} - {{handler}}"
    }
   ]
  },
  {
   "title": "registry request size 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(registry_http_request_size_bytes_bucket{instance=~\"$instance\"}[10m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "registry response size 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(registry_http_response_size_bytes_bucket{instance=~\"$instance\"}[10m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "registry storage action time 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(registry_storage_action_seconds_bucket{instance=~\"$instance\"}[10m]))",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}