{
 "title": "KubeVirt VM Info",
 "description": "KubeVirt VM Info",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kubevirt_vmi_cpu_usage_seconds_total,namespace)"
    }
   },
   {
    "name": "vm",
    "label": "vm",
    "query": {
     "query": "label_values(kubevirt_vmi_cpu_usage_seconds_total{namespace=\"$namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(kubevirt_vmi_vcpu_seconds_total{namespace=\"$namespace\", name=\"$vm\"}[5m])) by (domain, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Usage of VM (on Node)",
   "type": "timeseries",
   "description": "NOT what is used IN VM",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_resident_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "RAM Available (Gast-OS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_available_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "RAM Used (Gast-OS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_used_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "RAM Usable (Gast-OS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_usable_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "usable"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_iops_read_total{namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-read"
    },
    {
     "expr": "irate(kubevirt_vmi_storage_iops_write_total{namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-write"
    }
   ]
  },
  {
   "title": "IO Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_read_traffic_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-read"
    },
    {
     "expr": "irate(kubevirt_vmi_storage_write_traffic_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-write"
    }
   ]
  },
  {
   "title": "IO Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_read_times_seconds_total{namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-read"
    },
    {
     "expr": "irate(kubevirt_vmi_storage_write_times_seconds_total{namespace=\"$namespace\", name=\"$vm\"}[1m])",
     "legendFormat": "{{drive}}-write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true
  }
 ]
}