{
 "title": "VPA Recommendations - ONZACK",
 "description": "A dashboard to visualize metrics about the Vertical Pod Autoscaler (https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) using the generated Prometheus metrics of the Kube-State-Metrics (https://github.com/kubernetes/kube-state-metrics/blob/master/docs/verticalpodautoscaler-metrics.md)",
 "tags": [
  "Autoscaling",
  "VPA"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus Datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu,namespace)"
    }
   },
   {
    "name": "targetName",
    "label": "Target",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\"},target_name)"
    }
   },
   {
    "name": "vpa",
    "label": "VPA",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\", target_name=\"$targetName\"},verticalpodautoscaler)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\", target_name=\"$targetName\", verticalpodautoscaler=\"$vpa\"},container)"
    }
   },
   {
    "name": "pods",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\", target_name=\"$targetName\", verticalpodautoscaler=\"$vpa\"},target_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Recommendation Upperbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound_cpu{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPA CPU Recommendation vs CPU Usage",
   "type": "timeseries",
   "description": "Shows the recommendation that the VPA calculates. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 12, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\".*$targetName-(.+)\", container=~\"$container\"}[2m])) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}: Actual Usage"
    },
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "Recommendation Target"
    },
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "Recommendation Lowerbound"
    },
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "Recommendation Upperbound"
    }
   ]
  },
  {
   "title": "VPA CPU Recommendation vs Limits & Requests",
   "type": "timeseries",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{cluster=\"$cluster\", namespace=\"$namespace\", target_name=\"$targetName\", container=~\"$container\", resource=\"cpu\", verticalpodautoscaler=~\"$vpa\"}) by (container) ",
     "legendFormat": "Recommendation Target"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$targetName(.+)\", container=~\"$container\"}) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}: Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$targetName(.+)\", container=~\"$container\"}) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}: Limits"
    }
   ]
  },
  {
   "title": "Rec. Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{cluster=\"$cluster\", namespace=\"$namespace\", target_name=\"$targetName\", container=~\"$container\", resource=\"cpu\", verticalpodautoscaler=~\"$vpa\"}) by (container) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual Usage",
   "type": "stat",
   "description": "If there are several containers, the average is calculated",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$targetName-(.+)\", container=~\"$container\"}[2m])) by(container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommendation Lowerbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_vpa_containerrecommendations_lowerbound{resource=\"cpu\", cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Recommendation Upperbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound_memory{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPA Memory Recommendation vs Memory Usage",
   "type": "timeseries",
   "description": "Shows the recommendations that the VPA calculates. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 12, "w": 11, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$targetName(.+)\", container=~\"$container\"}) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}: Actual Usage"
    },
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "Recommendation Target"
    },
    {
     "expr": "sum(kube_customresource_vpa_containerrecommendations_lowerbound{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "Recommendation Lowerbound"
    },
    {
     "expr": "sum(kube_customresource_vpa_containerrecommendations_upperbound{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "Recommendation Upperbound"
    }
   ]
  },
  {
   "title": "VPA Memory Recommendation vs Limits & Requests",
   "type": "timeseries",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{cluster=\"$cluster\", namespace=\"$namespace\", target_name=\"$targetName\", container=~\"$container\", resource=\"memory\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "Recommendation Target"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$targetName(.+)\", container=~\"$container\"}) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}: Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$targetName(.+)\", container=~\"$container\"}) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}: Limits"
    }
   ]
  },
  {
   "title": "Recommendation Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", target_name=\"$targetName\", container=~\"$container\", verticalpodautoscaler=~\"$vpa\"}) by (container) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual Usage",
   "type": "stat",
   "description": "If there are several containers, the average is calculated",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$targetName(.+)\", container=~\"$container\"}) by(container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommendation Lowerbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_vpa_containerrecommendations_lowerbound{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\", verticalpodautoscaler=~\"$vpa\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total Evictions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {namespace=\"vpa\"} |= `reason=\"EvictedPod\"` | logfmt | pattern `<_> object=\"<namespace_extracted>/<vpa>\" <_> Pod <pod_extracted> <_>` \n    | namespace_extracted=~\"$namespace\" | vpa=~\"$vpa\"\n  [$__range])\n)"
    }
   ]
  },
  {
   "title": "Out of Memory Detections (OOM) & Eviction Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 2, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"vpa\"} |= `reason=\"EvictedPod\"` | logfmt | pattern `<_> object=\"<namespace_extracted>/<vpa>\" <_> Pod <pod_extracted> <_>` \n| namespace_extracted=~\"$namespace\" | vpa=~\"$vpa\"\n| line_format `VPA Updater evicted Pod {{.pod_extracted}} in Namespace {{.namespace_extracted}} to apply resource recommendation (VPA resource: {{.vpa}}).`",
     "legendFormat": "Evictions"
    },
    {
     "direction": "backward",
     "expr": "{namespace=\"vpa\"} |= `\"OOM detected\"` \n| pattern `<_> oomInfo={\"Timestamp\":\"<oom_timestamp>\",\"Memory\":<memory>,\"ContainerID\":{\"Namespace\":\"<namespace_extracted>\",\"PodName\":\"<pod_extracted>\",\"ContainerName\":\"<container_extracted>\"}}`\n| namespace_extracted=~\"$namespace\"\n| line_format \"OOM detected at {{.oom_timestamp}} for Container {{.container_extracted}} in Pod {{.pod_extracted}} in Namespace {{.namespace_extracted}} (Last observed memory used: {{div .memory 1048576 }}MB).\"",
     "legendFormat": "OOM Detection"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 27 },
   "targets": [
    {
     "expr": "count_over_time(\n    {namespace=\"vpa\"} |= `reason=\"EvictedPod\"` | logfmt | pattern `<_> object=\"<namespace_extracted>/<vpa>\" <_> Pod <pod_extracted> <_>` \n    | namespace_extracted=~\"$namespace\" | vpa=~\"$vpa\"\n[10m])",
     "legendFormat": "{{namespace_extracted}}/{{pod_extracted}}"
    }
   ]
  },
  {
   "title": "OOM Detections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {namespace=\"vpa\"} |= \"OOM detected\" |= `\"Namespace\":\"$namespace\"`\n  [$__range])\n)"
    }
   ]
  },
  {
   "title": "Reasons for not evicting Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 33 },
   "targets": [
    {
     "expr": "count by(namespace_extracted,pod_extracted,reason)(\n    count_over_time(\n        {namespace=\"vpa\"} |= `Not updating` | pattern `<_> \"<reason>\" pod=\"<namespace_extracted>/<pod_extracted>\"` \n        | namespace_extracted=~\"$namespace\" |~ \"$pods.+\"\n    [2m])\n)",
     "legendFormat": "{{pod_extracted}}: {{reason}}"
    }
   ]
  }
 ]
}