{
 "title": "VPA Recommendations",
 "description": "A dashboard to visualize metrics about the Vertical Pod Autoscalar (https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) using the generated Prometheus metrics of the Kube-State-Metrics (https://github.com/kubernetes/kube-state-metrics/blob/master/docs/verticalpodautoscaler-metrics.md)",
 "tags": [
  "Autoscaling",
  "VPA"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu,namespace)"
    }
   },
   {
    "name": "targetkind",
    "label": "Kind",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\"},target_kind)"
    }
   },
   {
    "name": "targetName",
    "label": "Target",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\", target_kind=\"$targetkind\"},target_name)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\", target_kind=\"$targetkind\", target_name=\"$targetName\"},container)"
    }
   },
   { "name": "recommendationType", "label": "Recommendation", "query": "target,upperbound,lowerbound" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rec. Upper",
   "type": "stat",
   "description": "Recommendation Upperbound CPU in Milicores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound_cpu{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\"}) by (container) * 1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU ${recommendationType} vs CPU Usage",
   "type": "timeseries",
   "description": "Shows the recommendations that the VPA gives as target usage. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$targetName-.*\", container=~\"$container\", container!=\"\", container!=\"POD\"}[$__rate_interval])) by (container, pod) * 1000",
     "legendFormat": "{{pod}}-{{container}} actual usage"
    },
    {
     "expr": "sum by(container) (\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_${recommendationType}_cpu{\n    namespace=\"$namespace\",\n    target_kind=\"$targetkind\", \n    target_name=\"$targetName\",\n    container=~\"$container\"\n  }\n) * 1000\n",
     "legendFormat": "{{container}} ${recommendationType} CPU"
    }
   ]
  },
  {
   "title": "VPA CPU ${recommendationType} vs Requests and Limits",
   "type": "timeseries",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(container) (kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_${recommendationType}_cpu{namespace=\"$namespace\", target_name=\"$targetName\"}) * 1000",
     "legendFormat": "{{container}} ${recommendationType} CPU"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", pod=~\"$targetName-.*\", container=~\"$container\"}) by (container,pod) * 1000",
     "legendFormat": "{{pod}}-{{container}} requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", pod=~\"$targetName-.*\", container=~\"$container\"}) by (container,pod) * 1000",
     "legendFormat": "{{pod}}-{{container}} limits"
    }
   ]
  },
  {
   "title": "Rec. Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_cpu{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\"}) by (container) *1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual",
   "type": "stat",
   "description": "Actual CPU Utilization",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\".*$targetName-(.+)\", container=~\"$container\"}[2m])) by(container) *1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rec. Lower",
   "type": "stat",
   "description": "Recommendation Lowerbound",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound_cpu{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\"}) by (container) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Rec. Upper",
   "type": "stat",
   "description": "Recommendation Upperbound Memory",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound_memory{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory ${recommendationType} vs Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$targetName-.*\", container=~\"$container\"}) by (container, pod)",
     "legendFormat": "{{pod}}-{{container}} actual usage"
    },
    {
     "expr": "sum by(container) (kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_${recommendationType}_memory{namespace=\"$namespace\", target_name=\"$targetName\"})",
     "legendFormat": "{{container}} ${recommendationType} Memory"
    }
   ]
  },
  {
   "title": "VPA Memory ${recommendationType} vs Requests and Limits",
   "type": "timeseries",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container) (kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_${recommendationType}_memory{namespace=\"$namespace\", target_name=\"$targetName\"})",
     "legendFormat": "{{container}} ${recommendationType} Memory"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod=~\"$targetName-.*\", container=~\"$container\"}) by (container,pod)",
     "legendFormat": "{{pod}}-{{container}} requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=~\"$targetName-.*\", container=~\"$container\"}) by (container,pod)",
     "legendFormat": "{{pod}}-{{container}} limits"
    }
   ]
  },
  {
   "title": "Rec. Target",
   "type": "stat",
   "description": "Recommendation Target Memory",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target_memory{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual Usage",
   "type": "stat",
   "description": "If there are several containers, the average is calculated",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\".*$targetName(.+)\", container=~\"$container\"}) by(container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rec. Target",
   "type": "stat",
   "description": "Recommendation Target Memory",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound_memory{namespace=\"$namespace\", container=~\"$container\", target_name=\"$targetName\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}